name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ "main" ] # 코드를 'main' 브랜치에 푸시할 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest # Linux 환경에서 .NET Core 빌드가 더 빠릅니다.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          # 고객님의 프로젝트가 .NET 8.0을 사용하는 것으로 보이므로 8.0.x를 사용합니다.
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        # 프로젝트 폴더로 이동해야 할 수도 있습니다. 필요한 경우 경로를 조정하세요.
        run: dotnet restore 

      - name: Publish Blazor WASM (Build)
        # 릴리스 모드로 빌드하며, 출력 경로는 자동으로 정해집니다.
        run: dotnet publish WebASMTimeTabler/WebASMTimeTabler.csproj -c Release -o ./publish_output --nologo 
        
      - name: Patch Base Href for GitHub Pages
        # 배포 폴더로 이동
        working-directory: ./publish_output/wwwroot
        # index.html 파일 내의 <base href="/" />를 <base href="/AutoTimeTableMaker/" />로 변경
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/AutoTimeTableMaker\/" \/>/g' index.html
          # 404.html 파일도 동일하게 수정합니다.
          sed -i 's/<base href="\/" \/>/<base href="\/AutoTimeTableMaker\/" \/>/g' 404.html
          
          echo "" > .nojekyll
          echo "Generated .nojekyll file in the deployment directory."

      # ----------------------------------------------------------------------
      # 핵심 배포 단계: 빌드된 파일을 gh-pages 브랜치에 푸시합니다.
      # ----------------------------------------------------------------------
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # dotnet publish 명령의 표준 출력 경로를 지정합니다. 
          # 경로는 'bin/Release/{TargetFramework}/publish/wwwroot' 형태입니다.
          publish_dir: ./publish_output/wwwroot 
          publish_branch: gh-pages # GitHub Pages가 읽을 브랜치
          
          # **중요:** Blazor WASM 라우팅을 위해 .nojekyll 파일을 추가합니다.
          # 이는 GitHub Pages에서 특수 파일 처리를 비활성화하여 _framework 폴더 등이 제대로 로드되게 합니다.
          enable_jekyll: true
